
CUST_ACCT_TYPE_CODE
amt_email_pmt_14d_cap
amt_rvsd_cap
amt_txn_refund_l180d_cap
amt_avg_balance_l60d_cap
amt_avg_balance_l14d_cap
amt_ach_90d_cap
amt_ach_14d_cap
amt_ach_30d_cap
amt_nsf_ach_14d_cap


